<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <AssemblyName>Delivery List Scanner</AssemblyName>
    <ApplicationIcon>..\assets\delivery-list-scanner-icon.ico</ApplicationIcon>
    <UseAppHost>true</UseAppHost>
  </PropertyGroup>
</Project>
